[package]
name = "news-letter"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4"
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
